"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { Clock3, Loader2, ShoppingBag, Sparkles } from "lucide-react";
import type { MarketplaceAvailability, MarketplaceItem } from "@/lib/marketplace";
import { MARKETPLACE_FLOOR_PERCENT, marketplacePrice, parseCharlestonDateTime } from "@/lib/marketplace-pricing";

const money=(n:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(n);
function countdown(end:string,now:number){const target=parseCharlestonDateTime(end)?.getTime()||now;let s=Math.max(0,Math.floor((target-now)/1000));const d=Math.floor(s/86400);s%=86400;const h=Math.floor(s/3600);s%=3600;const m=Math.floor(s/60);const sec=s%60;return `${d}d ${String(h).padStart(2,"0")}h ${String(m).padStart(2,"0")}m ${String(sec).padStart(2,"0")}s`;}

export function MarketplaceExperience({items,initialAvailability}:{items:MarketplaceItem[];initialAvailability:MarketplaceAvailability[]}){
 const [now,setNow]=useState(Date.now()); const [availability,setAvailability]=useState(initialAvailability); const [active,setActive]=useState<MarketplaceItem|null>(null); const [submitting,setSubmitting]=useState(false); const [error,setError]=useState(""); const [success,setSuccess]=useState<{title:string;price:number;orderId:string}|null>(null);
 useEffect(()=>{const t=window.setInterval(()=>setNow(Date.now()),100);return()=>window.clearInterval(t)},[]);
 useEffect(()=>{const t=window.setInterval(async()=>{try{const r=await fetch("/api/marketplace/status",{cache:"no-store"});const d=await r.json();if(r.ok&&d.ok)setAvailability(d.availability)}catch{}},10000);return()=>window.clearInterval(t)},[]);
 const map=useMemo(()=>new Map(availability.map(a=>[a.itemId,a])),[availability]);
 async function claim(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!active)return;setSubmitting(true);setError("");const f=new FormData(e.currentTarget);try{const r=await fetch("/api/marketplace/claim",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({itemId:active.ID,name:f.get("name"),email:f.get("email"),phone:f.get("phone"),accepted:f.get("accepted")==="on",website:f.get("website")})});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||"Could not reserve item.");setAvailability(p=>p.map(a=>a.itemId===active.ID?{...a,claimed:a.claimed+1,remaining:Math.max(0,d.remaining)}:a));setSuccess({title:active.Title,price:d.price,orderId:d.orderId});setActive(null)}catch(err){setError(err instanceof Error?err.message:"Could not reserve item.")}finally{setSubmitting(false)}}
 return <>
  <section className="mx-auto max-w-6xl px-6 pt-8"><div className="rounded-2xl border border-gold-200 bg-white p-5 text-center shadow-sm"><p className="text-sm font-semibold text-navy-800">Every price starts at full retail and continuously falls until it reaches {MARKETPLACE_FLOOR_PERCENT}% of retail at event close.</p><p className="mt-1 text-sm text-navy-500">Wait and the price gets better. Wait too long and someone else can make it theirs.</p></div></section>
  <section className="mx-auto grid max-w-6xl gap-6 px-6 py-10 md:grid-cols-2 lg:grid-cols-3">{items.map(item=>{const p=marketplacePrice(item,new Date(now));const a=map.get(item.ID);const remaining=a?.remaining??Math.max(1,Number(item.Quantity)||1);const sold=remaining<=0;return <article key={item.ID} className={`overflow-hidden rounded-2xl border bg-white shadow-sm ${item.Featured==="TRUE"?"border-gold-400 ring-1 ring-gold-200":"border-navy-100"}`}>
   {item.PhotoURL?<img src={item.PhotoURL} alt={item.Title} className="h-56 w-full object-cover"/>:<div className="flex h-56 items-center justify-center bg-cream-200 text-gold-600"><ShoppingBag className="h-10 w-10"/></div>}
   <div className="p-6">{item.Featured==="TRUE"&&<p className="mb-2 flex items-center gap-1 text-xs font-bold uppercase tracking-[.18em] text-gold-700"><Sparkles className="h-3.5 w-3.5"/>Featured drop</p>}<h3 className="font-serif text-2xl font-bold text-navy-800">{item.Title}</h3>{item.DonorName&&<p className="mt-1 text-xs font-semibold uppercase tracking-wide text-navy-400">Provided by {item.DonorName}</p>}{item.Description&&<p className="mt-4 whitespace-pre-line text-sm leading-6 text-navy-600">{item.Description}</p>}
   <div className="mt-5 rounded-xl bg-cream-100 p-4"><div className="flex items-end justify-between gap-3"><div><p className="text-[11px] uppercase tracking-wide text-navy-400">Make It Mine price</p><p className="font-serif text-3xl font-bold text-navy-800">{money(p.price)}</p></div><div className="text-right"><p className="text-xs text-navy-400 line-through">Retail {money(Number(item.RetailValue))}</p><p className="text-sm font-bold text-green-700">{p.percentBelowRetail.toFixed(1)}% below retail</p></div></div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-white"><div className="h-full bg-gold-500 transition-[width] duration-100" style={{width:`${Math.max(0,Math.min(100,p.progress*100))}%`}}/></div><p className="mt-3 flex items-center justify-center gap-1 text-xs font-semibold text-navy-600"><Clock3 className="h-3.5 w-3.5"/> Price floor in {countdown(item.EndAt,now)}</p></div>
   <p className="mt-3 text-center text-xs font-semibold uppercase tracking-wide text-red-600">{remaining===1?"Only 1 available":`${remaining} available`} · first completed claim gets it</p>
   {sold?<div className="mt-4 rounded-md bg-navy-100 px-4 py-3 text-center text-sm font-bold text-navy-700">SOLD · SOMEONE MADE IT THEIRS</div>:!p.started?<div className="mt-4 rounded-md bg-cream-200 px-4 py-3 text-center text-sm font-bold text-navy-700">PRICE DROP STARTS SOON</div>:p.ended?<div className="mt-4 rounded-md bg-navy-100 px-4 py-3 text-center text-sm font-bold text-navy-700">DROP ENDED</div>:<button onClick={()=>{setActive(item);setError("")}} className="mt-4 w-full rounded-md bg-gold-600 px-5 py-3 text-sm font-bold uppercase tracking-wide text-navy-900 shadow-sm hover:bg-gold-700">MAKE THIS MINE — {money(p.price)}</button>}
   {item.PickupDetails&&<p className="mt-4 text-xs leading-5 text-navy-500"><strong>Fulfillment:</strong> {item.PickupDetails}</p>}{item.Terms&&<p className="mt-2 text-xs leading-5 text-navy-500"><strong>Terms:</strong> {item.Terms}</p>}</div></article>})}</section>
  {active&&<div className="fixed inset-0 z-[100] flex items-center justify-center bg-navy-900/70 p-4"><form onSubmit={claim} className="w-full max-w-md rounded-2xl bg-white p-6 shadow-xl"><p className="text-xs font-bold uppercase tracking-[.2em] text-gold-700">Lock the current price</p><h2 className="mt-2 font-serif text-2xl font-bold text-navy-800">Make {active.Title} mine</h2><p className="mt-2 text-sm text-navy-600">Your purchase price is recalculated and locked by the server when you submit. If another shopper claims the last available unit first, your request will not be accepted.</p><div className="mt-5 space-y-3"><input required name="name" placeholder="Full name" className="w-full rounded-md border border-navy-100 px-3 py-2.5 text-sm"/><input required type="email" name="email" placeholder="Email" className="w-full rounded-md border border-navy-100 px-3 py-2.5 text-sm"/><input required name="phone" placeholder="Mobile phone" className="w-full rounded-md border border-navy-100 px-3 py-2.5 text-sm"/><input name="website" className="hidden" tabIndex={-1}/><label className="flex gap-2 text-xs leading-5 text-navy-600"><input required type="checkbox" name="accepted" className="mt-1"/>I agree to purchase this item at the price locked when I submit. SC Wellness Weekend will send secure payment and fulfillment instructions. Applicable tax, if any, is handled at payment.</label></div>{error&&<p className="mt-3 text-sm text-red-600">{error}</p>}<button disabled={submitting} className="mt-5 inline-flex w-full items-center justify-center gap-2 rounded-md bg-gold-600 px-5 py-3 text-sm font-bold uppercase tracking-wide text-navy-900">{submitting&&<Loader2 className="h-4 w-4 animate-spin"/>MAKE THIS MINE</button><button type="button" onClick={()=>setActive(null)} className="mt-2 w-full px-4 py-2 text-sm text-navy-500">Keep watching the price</button></form></div>}
  {success&&<div className="fixed inset-0 z-[110] flex items-center justify-center bg-navy-900/70 p-4"><div className="w-full max-w-md rounded-2xl bg-white p-7 text-center shadow-xl"><Sparkles className="mx-auto h-9 w-9 text-gold-600"/><h2 className="mt-3 font-serif text-3xl font-bold text-navy-800">It’s yours.</h2><p className="mt-3 text-navy-600">{success.title} has been locked to you at <strong>{money(success.price)}</strong>.</p><p className="mt-2 text-xs text-navy-500">Order {success.orderId}. Payment and fulfillment instructions will be sent to the contact information you provided.</p><button onClick={()=>setSuccess(null)} className="mt-5 rounded-md bg-navy-800 px-6 py-3 text-sm font-bold uppercase tracking-wide text-white">Continue shopping</button></div></div>}
 </>;
}
