import{createHmac,timingSafeEqual}from"node:crypto";
export interface HostedCheckoutInput{orderId:string;amount:number;itemTitle:string;email:string;returnUrl:string;cancelUrl:string}
export interface AuthorizeNetTransactionDetails{transactionId:string;status:string;amount:number;invoiceNumber:string;email?:string;responseCode?:number;cardLast4?:string}
function configured(){return Boolean(process.env.AUTHORIZENET_API_LOGIN_ID&&process.env.AUTHORIZENET_TRANSACTION_KEY)}
export function authorizeNetConfigured(){return configured()}
export function authorizeNetPaymentUrl(){return(process.env.AUTHORIZENET_ENVIRONMENT||"production").toLowerCase()==="sandbox"?"https://test.authorize.net/payment/payment":"https://accept.authorize.net/payment/payment"}
function apiUrl(){return(process.env.AUTHORIZENET_ENVIRONMENT||"production").toLowerCase()==="sandbox"?"https://apitest.authorize.net/xml/v1/request.api":"https://api.authorize.net/xml/v1/request.api"}
function messageText(value:any){const messages=value?.messages?.message;return Array.isArray(messages)?messages.map((m:any)=>m?.text).filter(Boolean).join(" "):messages?.text||"Authorize.Net did not return a valid response."}
function merchantAuthentication(){return{name:process.env.AUTHORIZENET_API_LOGIN_ID,transactionKey:process.env.AUTHORIZENET_TRANSACTION_KEY}}
export function marketplaceInvoiceNumber(orderId:string){return orderId.replace(/[^a-zA-Z0-9_-]/g,"-").slice(0,20)}
export async function createAuthorizeNetHostedToken(input:HostedCheckoutInput){if(!configured())return null;const request={getHostedPaymentPageRequest:{merchantAuthentication:merchantAuthentication(),refId:input.orderId,transactionRequest:{transactionType:"authCaptureTransaction",amount:input.amount.toFixed(2),order:{invoiceNumber:marketplaceInvoiceNumber(input.orderId),description:input.itemTitle.slice(0,255)},customer:{email:input.email}},hostedPaymentSettings:{setting:[{settingName:"hostedPaymentReturnOptions",settingValue:JSON.stringify({showReceipt:true,url:input.returnUrl,urlText:"Return to SC Wellness Weekend",cancelUrl:input.cancelUrl,cancelUrlText:"Return to Marketplace"})},{settingName:"hostedPaymentButtonOptions",settingValue:JSON.stringify({text:`Pay $${input.amount.toFixed(2)}`})},{settingName:"hostedPaymentPaymentOptions",settingValue:JSON.stringify({cardCodeRequired:true,showCreditCard:true,showBankAccount:false})},{settingName:"hostedPaymentBillingAddressOptions",settingValue:JSON.stringify({show:true,required:false})},{settingName:"hostedPaymentCustomerOptions",settingValue:JSON.stringify({showEmail:true,requiredEmail:true,addPaymentProfile:false})},{settingName:"hostedPaymentOrderOptions",settingValue:JSON.stringify({show:true,merchantName:"South Carolina Wellness Weekend"})}]}}};const response=await fetch(apiUrl(),{method:"POST",headers:{"Content-Type":"application/json","Accept":"application/json"},body:JSON.stringify(request),cache:"no-store"});const raw=await response.text();let data:any;try{data=JSON.parse(raw.replace(/^\uFEFF/,""))}catch{throw new Error("Authorize.Net returned an unreadable response.")}if(!response.ok||data?.messages?.resultCode!=="Ok"||!data?.token)throw new Error(messageText(data));return{token:String(data.token),paymentUrl:authorizeNetPaymentUrl()}}
export async function getAuthorizeNetTransactionDetails(transactionId:string):Promise<AuthorizeNetTransactionDetails>{if(!configured())throw new Error("Authorize.Net is not configured.");const request={getTransactionDetailsRequest:{merchantAuthentication:merchantAuthentication(),transId:transactionId}};const response=await fetch(apiUrl(),{method:"POST",headers:{"Content-Type":"application/json","Accept":"application/json"},body:JSON.stringify(request),cache:"no-store"});const raw=await response.text();let data:any;try{data=JSON.parse(raw.replace(/^\uFEFF/,""))}catch{throw new Error("Authorize.Net returned an unreadable transaction response.")}if(!response.ok||data?.messages?.resultCode!=="Ok"||!data?.transaction)throw new Error(messageText(data));const tx=data.transaction;return{transactionId:String(tx.transId||transactionId),status:String(tx.transactionStatus||""),amount:Number(tx.authAmount??tx.settleAmount??0),invoiceNumber:String(tx.order?.invoiceNumber||""),email:tx.customer?.email?String(tx.customer.email):undefined,responseCode:tx.responseCode!=null?Number(tx.responseCode):undefined,cardLast4:tx.payment?.creditCard?.cardNumber?String(tx.payment.creditCard.cardNumber).replace(/\D/g,"").slice(-4):undefined}}
export function authorizeNetTransactionIsPaid(details:AuthorizeNetTransactionDetails){return details.responseCode===1&&["capturedPendingSettlement","settledSuccessfully"].includes(details.status)}
export async function refundAuthorizeNetTransaction(transactionId:string,amount:number,cardLast4:string){if(!configured())throw new Error("Authorize.Net is not configured.");if(!/^\d{4}$/.test(cardLast4))throw new Error("The original card last four digits are unavailable for refund.");const request={createTransactionRequest:{merchantAuthentication:merchantAuthentication(),transactionRequest:{transactionType:"refundTransaction",amount:amount.toFixed(2),payment:{creditCard:{cardNumber:cardLast4,expirationDate:"XXXX"}},refTransId:transactionId}}};const response=await fetch(apiUrl(),{method:"POST",headers:{"Content-Type":"application/json","Accept":"application/json"},body:JSON.stringify(request),cache:"no-store"});const raw=await response.text();let data:any;try{data=JSON.parse(raw.replace(/^\uFEFF/,""))}catch{throw new Error("Authorize.Net returned an unreadable refund response.")}const tx=data?.transactionResponse;if(!response.ok||data?.messages?.resultCode!=="Ok"||String(tx?.responseCode||"")!=="1"||!tx?.transId)throw new Error(tx?.errors?.[0]?.errorText||messageText(data));return{transactionId:String(tx.transId),responseCode:Number(tx.responseCode)} }
export function authorizeNetWebhookDiagnostics(signatureHeader:string|null){const key=(process.env.AUTHORIZENET_SIGNATURE_KEY||"").replace(/\s+/g,"");const supplied=(signatureHeader||"").replace(/^sha512=/i,"").trim();return{keyConfigured:Boolean(key),keyHex:/^[0-9a-f]+$/i.test(key),keyLength:key.length,signaturePresent:Boolean(signatureHeader),signatureHex:/^[0-9a-f]{128}$/i.test(supplied),signatureLength:supplied.length}}
export function verifyAuthorizeNetWebhook(rawBody:Uint8Array,signatureHeader:string|null){const key=(process.env.AUTHORIZENET_SIGNATURE_KEY||"").replace(/\s+/g,"");if(!key||!signatureHeader)return false;const supplied=signatureHeader.replace(/^sha512=/i,"").trim().toLowerCase();if(!/^[0-9a-f]{128}$/i.test(supplied)||!/^[0-9a-f]+$/i.test(key)||key.length%2!==0)return false;const expected=createHmac("sha512",Buffer.from(key,"hex")).update(rawBody).digest("hex").toLowerCase();const a=Buffer.from(expected,"hex"),b=Buffer.from(supplied,"hex");return a.length===b.length&&timingSafeEqual(a,b)}
