import{createCipheriv,createDecipheriv,createHash,randomBytes}from"node:crypto";import{del,list,put}from"@vercel/blob";import{marketplacePrice}from"@/lib/marketplace-pricing";
export const MARKETPLACE_ITEM_PREFIX="sc-wellness-marketplace/items/";export const MARKETPLACE_CLAIM_PREFIX="sc-wellness-marketplace/claims/";
export interface MarketplaceItem{ID:string;Title:string;PhotoURL:string;Description:string;DonorName:string;RetailValue:string;LaunchAt:string;EndAt:string;FloorPercent:string;Quantity:string;PickupDetails:string;Terms:string;TaxCategory:string;Featured:string;Published:string;UpdatedAt:string;}
export interface MarketplaceAvailability{itemId:string;claimed:number;quantity:number;remaining:number;lockedPrice?:number;orderId?:string;claimedAt?:string;paymentStatus?:"PENDING"|"PAID"|"REFUNDED";transactionId?:string;paidAt?:string;refundedAt?:string;refundTransactionId?:string;}
export interface MarketplaceOrderPayload{orderId:string;itemId:string;itemTitle:string;price:number;retailValue:number;claimedAt:string;name:string;email:string;phone:string;paymentStatus?:"PENDING"|"PAID"|"REFUNDED";transactionId?:string;paidAt?:string;refundedAt?:string;refundTransactionId?:string;}
function truthy(value?:string){return["true","yes","1","y"].includes((value||"").trim().toLowerCase())}function storageId(value:string){return createHash("sha256").update(value).digest("hex").slice(0,32)}function claimPath(itemId:string){return`${MARKETPLACE_CLAIM_PREFIX}${storageId(itemId)}.enc`}function requireStorage(){if(!process.env.BLOB_READ_WRITE_TOKEN&&!process.env.BLOB_STORE_ID)throw new Error("Marketplace storage is not configured.")}async function readJson<T>(url:string,uploadedAt?:Date):Promise<T>{const separator=url.includes("?")?"&":"?";const response=await fetch(`${url}${separator}v=${uploadedAt?.getTime()||Date.now()}`,{cache:"no-store"});if(!response.ok)throw new Error("Marketplace listing storage could not be read.");return await response.json()as T}function normalizeItem(item:MarketplaceItem){return{...item,FloorPercent:String(item.FloorPercent||"15")}}function isMarketplaceItem(value:unknown):value is MarketplaceItem{if(!value||typeof value!=="object")return false;const item=value as Partial<MarketplaceItem>;return typeof item.ID==="string"&&typeof item.Title==="string"&&typeof item.RetailValue==="string"&&Number(item.RetailValue)>0&&typeof item.LaunchAt==="string"&&typeof item.EndAt==="string"&&typeof item.Published==="string"}
export async function fetchMarketplaceItems(options:{publishedOnly?:boolean}={}){requireStorage();const result=await list({prefix:MARKETPLACE_ITEM_PREFIX,limit:1000});const items=(await Promise.all(result.blobs.map(blob=>readJson<unknown>(blob.url,blob.uploadedAt)))).filter(isMarketplaceItem).map(normalizeItem).sort((a,b)=>Number(b.Featured==="TRUE")-Number(a.Featured==="TRUE")||a.Title.localeCompare(b.Title));return options.publishedOnly?items.filter(item=>truthy(item.Published)):items}
export async function saveMarketplaceItem(item:MarketplaceItem){requireStorage();await put(`${MARKETPLACE_ITEM_PREFIX}${storageId(item.ID)}.json`,JSON.stringify(item),{access:"public",allowOverwrite:true,addRandomSuffix:false,contentType:"application/json",cacheControlMaxAge:60})}
function encryptionKey(){const secret=process.env.ADMIN_API_SECRET||process.env.ADMIN_PASSWORD||"";if(!secret)throw new Error("Marketplace reservation encryption is not configured.");return createHash("sha256").update(secret).digest()}function encryptOrder(payload:MarketplaceOrderPayload){const iv=randomBytes(12);const cipher=createCipheriv("aes-256-gcm",encryptionKey(),iv);const encrypted=Buffer.concat([cipher.update(JSON.stringify(payload),"utf8"),cipher.final()]);return JSON.stringify({iv:iv.toString("base64"),tag:cipher.getAuthTag().toString("base64"),data:encrypted.toString("base64")})}function decryptOrder(raw:string):MarketplaceOrderPayload{const envelope=JSON.parse(raw)as{iv:string;tag:string;data:string};const decipher=createDecipheriv("aes-256-gcm",encryptionKey(),Buffer.from(envelope.iv,"base64"));decipher.setAuthTag(Buffer.from(envelope.tag,"base64"));const plain=Buffer.concat([decipher.update(Buffer.from(envelope.data,"base64")),decipher.final()]).toString("utf8");return JSON.parse(plain)as MarketplaceOrderPayload}async function orderFromBlob(url:string,uploadedAt?:Date){const separator=url.includes("?")?"&":"?";const response=await fetch(`${url}${separator}v=${uploadedAt?.getTime()||Date.now()}`,{cache:"no-store"});if(!response.ok)throw new Error("Marketplace reservation could not be read.");return decryptOrder(await response.text())}
export async function marketplaceAvailability(items:MarketplaceItem[]){requireStorage();const claims=await list({prefix:MARKETPLACE_CLAIM_PREFIX,limit:1000});const byPath=new Map(claims.blobs.map(blob=>[blob.pathname,blob]));return Promise.all(items.map(async item=>{const blob=byPath.get(claimPath(item.ID));if(!blob)return{itemId:item.ID,claimed:0,quantity:1,remaining:1};try{const order=await orderFromBlob(blob.url,blob.uploadedAt);return{itemId:item.ID,claimed:1,quantity:1,remaining:0,lockedPrice:order.price,orderId:order.orderId,claimedAt:order.claimedAt,paymentStatus:order.paymentStatus||"PENDING",transactionId:order.transactionId,paidAt:order.paidAt,refundedAt:order.refundedAt,refundTransactionId:order.refundTransactionId}}catch{return{itemId:item.ID,claimed:1,quantity:1,remaining:0}}}))}
export async function marketplaceItemIsReserved(itemId:string){requireStorage();const path=claimPath(itemId);const result=await list({prefix:path,limit:2});const exact=result.blobs.filter(blob=>blob.pathname===path);if(exact.length>1)throw new Error("Marketplace reservation state is inconsistent.");return exact.length===1}
export async function getMarketplaceOrder(itemId:string){requireStorage();const path=claimPath(itemId);const result=await list({prefix:path,limit:2});const blob=result.blobs.find(candidate=>candidate.pathname===path);return blob?orderFromBlob(blob.url,blob.uploadedAt):null}
export async function findMarketplaceOrderByOrderId(orderId:string){requireStorage();const claims=await list({prefix:MARKETPLACE_CLAIM_PREFIX,limit:1000});for(const blob of claims.blobs){try{const order=await orderFromBlob(blob.url,blob.uploadedAt);if(order.orderId===orderId)return order}catch{}}return null}
export async function releaseMarketplaceItem(itemId:string){requireStorage();const path=claimPath(itemId);const result=await list({prefix:path,limit:2});const blob=result.blobs.find(candidate=>candidate.pathname===path);if(!blob)return false;await del(blob.url);return true}
export async function markMarketplaceOrderPaid(orderId:string,transactionId:string,paidAt=new Date().toISOString()){requireStorage();const claims=await list({prefix:MARKETPLACE_CLAIM_PREFIX,limit:1000});for(const blob of claims.blobs){try{const order=await orderFromBlob(blob.url,blob.uploadedAt);if(order.orderId!==orderId)continue;const updated:MarketplaceOrderPayload={...order,paymentStatus:"PAID",transactionId,paidAt};await put(claimPath(order.itemId),encryptOrder(updated),{access:"public",allowOverwrite:true,addRandomSuffix:false,contentType:"application/octet-stream",cacheControlMaxAge:60});return updated}catch{}}return null}
export async function markMarketplaceOrderRefunded(itemId:string,refundTransactionId:string,refundedAt=new Date().toISOString()){const order=await getMarketplaceOrder(itemId);if(!order)return null;const updated:MarketplaceOrderPayload={...order,paymentStatus:"REFUNDED",refundTransactionId,refundedAt};await put(claimPath(itemId),encryptOrder(updated),{access:"public",allowOverwrite:true,addRandomSuffix:false,contentType:"application/octet-stream",cacheControlMaxAge:60});return updated}
export async function claimMarketplaceItem(item:MarketplaceItem,contact:{name:string;email:string;phone:string}){requireStorage();encryptionKey();const pricing=marketplacePrice(item,new Date());const orderId=`order-${Date.now().toString(36)}-${randomBytes(3).toString("hex")}`;const claimedAt=new Date().toISOString();const payload:MarketplaceOrderPayload={orderId,itemId:item.ID,itemTitle:item.Title,price:Number(pricing.price.toFixed(2)),retailValue:Number(item.RetailValue),claimedAt,name:contact.name.trim(),email:contact.email.trim().toLowerCase(),phone:contact.phone.trim(),paymentStatus:"PENDING"};try{await put(claimPath(item.ID),encryptOrder(payload),{access:"public",allowOverwrite:false,addRandomSuffix:false,contentType:"application/octet-stream",cacheControlMaxAge:60})}catch{throw new Error("This item could not be reserved. It may have just been claimed; refresh the page before trying again.")}return{ok:true as const,orderId,slot:1,price:payload.price,remaining:0,payload}}
